// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9QH7AFfhb9Hd5-IVnfhrDUbkMeBoinB8',
    appId: '1:737846256314:web:98dc2f3e4ec5df449d1883',
    messagingSenderId: '737846256314',
    projectId: 'histreet-application',
    authDomain: 'histreet-application.firebaseapp.com',
    storageBucket: 'histreet-application.appspot.com',
    measurementId: 'G-56PNDYZ0S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrvzydqqSFbp0b0brSNYqU8bdphE-b8BI',
    appId: '1:737846256314:android:2a51c218b606fa709d1883',
    messagingSenderId: '737846256314',
    projectId: 'histreet-application',
    storageBucket: 'histreet-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPHHoSicCfVv2U2tesa2kHNanTgRHfBks',
    appId: '1:737846256314:ios:0be904e638ac38089d1883',
    messagingSenderId: '737846256314',
    projectId: 'histreet-application',
    storageBucket: 'histreet-application.appspot.com',
    iosBundleId: 'com.example.histreet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPHHoSicCfVv2U2tesa2kHNanTgRHfBks',
    appId: '1:737846256314:ios:0be904e638ac38089d1883',
    messagingSenderId: '737846256314',
    projectId: 'histreet-application',
    storageBucket: 'histreet-application.appspot.com',
    iosBundleId: 'com.example.histreet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9QH7AFfhb9Hd5-IVnfhrDUbkMeBoinB8',
    appId: '1:737846256314:web:db7db9d7b0f06bfa9d1883',
    messagingSenderId: '737846256314',
    projectId: 'histreet-application',
    authDomain: 'histreet-application.firebaseapp.com',
    storageBucket: 'histreet-application.appspot.com',
    measurementId: 'G-6RQPJN1VJL',
  );
}
